/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import { Contract, ContractFactory, Overrides } from "@ethersproject/contracts";

import type { PeripheryImmutableStateTest } from "../PeripheryImmutableStateTest";

export class PeripheryImmutableStateTest__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(
    _factory: string,
    _WETH9: string,
    overrides?: Overrides
  ): Promise<PeripheryImmutableStateTest> {
    return super.deploy(
      _factory,
      _WETH9,
      overrides || {}
    ) as Promise<PeripheryImmutableStateTest>;
  }
  getDeployTransaction(
    _factory: string,
    _WETH9: string,
    overrides?: Overrides
  ): TransactionRequest {
    return super.getDeployTransaction(_factory, _WETH9, overrides || {});
  }
  attach(address: string): PeripheryImmutableStateTest {
    return super.attach(address) as PeripheryImmutableStateTest;
  }
  connect(signer: Signer): PeripheryImmutableStateTest__factory {
    return super.connect(signer) as PeripheryImmutableStateTest__factory;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): PeripheryImmutableStateTest {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as PeripheryImmutableStateTest;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_factory",
        type: "address",
      },
      {
        internalType: "address",
        name: "_WETH9",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "WETH9",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "factory",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "poolDeployer",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x60e060405234801561001057600080fd5b506040516102223803806102228339818101604052604081101561003357600080fd5b5080516020918201516001600160601b0319606083811b821660805282901b1660a0526040805163188c824d60e11b8152905192939192849284926001600160a01b03851692633119049a92600480840193919291829003018186803b15801561009c57600080fd5b505afa1580156100b0573d6000803e3d6000fd5b505050506040513d60208110156100c657600080fd5b50516001600160601b031960609190911b1660c0525050505060805160601c60a05160601c60c05160601c610111610111600039806071525080609552508060b952506101116000f3fe6080604052348015600f57600080fd5b5060043610603c5760003560e01c80633119049a1460415780634aa4a4fc146063578063c45a0155146069575b600080fd5b6047606f565b604080516001600160a01b039092168252519081900360200190f35b60476093565b604760b7565b7f000000000000000000000000000000000000000000000000000000000000000081565b7f000000000000000000000000000000000000000000000000000000000000000081565b7f00000000000000000000000000000000000000000000000000000000000000008156fea264697066735822122078eea29352b8c5ff9347ef5a851bed35de352b19ee54fba43f77b5a50a516a2464736f6c63430007060033";
