/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import { Contract, ContractFactory, Overrides } from "@ethersproject/contracts";

import type { PoolAddressTest } from "../PoolAddressTest";

export class PoolAddressTest__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(overrides?: Overrides): Promise<PoolAddressTest> {
    return super.deploy(overrides || {}) as Promise<PoolAddressTest>;
  }
  getDeployTransaction(overrides?: Overrides): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): PoolAddressTest {
    return super.attach(address) as PoolAddressTest;
  }
  connect(signer: Signer): PoolAddressTest__factory {
    return super.connect(signer) as PoolAddressTest__factory;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): PoolAddressTest {
    return new Contract(address, _abi, signerOrProvider) as PoolAddressTest;
  }
}

const _abi = [
  {
    inputs: [],
    name: "POOL_INIT_CODE_HASH",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "poolDeployer",
        type: "address",
      },
      {
        internalType: "address",
        name: "token0",
        type: "address",
      },
      {
        internalType: "address",
        name: "token1",
        type: "address",
      },
      {
        internalType: "uint24",
        name: "fee",
        type: "uint24",
      },
    ],
    name: "computeAddress",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "poolDeployer",
        type: "address",
      },
      {
        internalType: "address",
        name: "token0",
        type: "address",
      },
      {
        internalType: "address",
        name: "token1",
        type: "address",
      },
      {
        internalType: "uint24",
        name: "fee",
        type: "uint24",
      },
    ],
    name: "getGasCostOfComputeAddress",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b506102d2806100206000396000f3fe608060405234801561001057600080fd5b50600436106100415760003560e01c80638716c5ff14610046578063cce34ec6146100a4578063dc6fd8ab146100f8575b600080fd5b6100886004803603608081101561005c57600080fd5b5080356001600160a01b03908116916020810135821691604082013516906060013562ffffff16610100565b604080516001600160a01b039092168252519081900360200190f35b6100e6600480360360808110156100ba57600080fd5b5080356001600160a01b03908116916020810135821691604082013516906060013562ffffff16610146565b60408051918252519081900360200190f35b6100e6610194565b600061013d856040518060600160405280876001600160a01b03168152602001866001600160a01b031681526020018562ffffff168152506101b8565b95945050505050565b6000805a9050610187866040518060600160405280886001600160a01b03168152602001876001600160a01b031681526020018662ffffff168152506101b8565b505a900395945050505050565b7f1b5c366cb0b7109926c0b161c0a85469fa485e75389d33a4dd753c35b22f157b90565b600081602001516001600160a01b031682600001516001600160a01b0316106101e057600080fd5b50805160208083015160409384015184516001600160a01b0394851681850152939091168385015262ffffff166060808401919091528351808403820181526080840185528051908301206001600160f81b031960a085015294901b6bffffffffffffffffffffffff191660a183015260b58201939093527f1b5c366cb0b7109926c0b161c0a85469fa485e75389d33a4dd753c35b22f157b60d5808301919091528251808303909101815260f590910190915280519101209056fea2646970667358221220db03e7f77c71f9949da7c3969916b93b1b0bd179143c4195eaf67c3437c1808064736f6c63430007060033";
